import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import { ru, pluralRu, localizeError } from '../src-tauri/frontend-dist/ru.js';
const src = fs.readFileSync(new URL('../src-tauri/frontend-dist/app.js', import.meta.url), 'utf8');
const sandbox = { ru };
vm.createContext(sandbox);
vm.runInContext(src.slice(src.indexOf('const translations ='), src.indexOf('const iconNames =')) + '\nthis.translations=translations;', sandbox);
for (const key of Object.keys(sandbox.translations.en)) assert.ok(key in ru, `Missing Russian key: ${key}`);
for (const [, key] of src.matchAll(/\bt\(['"]([^'"]+)['"]/g)) assert.ok(key in ru || key in sandbox.translations.en, `Unknown translation key: ${key}`);
for (const [n, expected] of [[1,'страница'],[2,'страницы'],[5,'страниц'],[11,'страниц'],[21,'страница'],[22,'страницы'],[25,'страниц'],[111,'страниц']]) assert.equal(pluralRu(n,'страница','страницы','страниц'), expected);
assert.match(localizeError('file_not_found'), /не найден/);
assert.equal(localizeError('Не удалось сохранить.'), 'Не удалось сохранить.');
const conf = JSON.parse(fs.readFileSync(new URL('../src-tauri/tauri.conf.json', import.meta.url)));
assert.equal(conf.identifier, 'com.rolexx671.slate.ru');
assert.equal(conf.productName, 'Slate RU');
assert.equal(conf.bundle.createUpdaterArtifacts, false);
assert.ok(!conf.plugins.updater);
assert.ok(!src.includes("invokeCommand('install_update')"));
assert.ok(!src.includes("invokeCommand('check_for_update')"));
assert.match(src, /language: 'ru'/);
assert.equal(conf.bundle.fileAssociations[0].rank, 'Alternate');
console.log(`Passed: ${Object.keys(ru).length} Russian entries, plural forms, error messages and isolated build configuration.`);
